load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "aliases",
    hdrs = ["aliases.h"],
    deps = [
        "@operational-space-controller//:operational_space_controller",
        "@eigen//:eigen",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "containers",
    hdrs = ["containers.h"],
    deps = [
        ":aliases",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "constants",
    hdrs = ["constants.h"],
    deps = [
        ":aliases",
        ":containers",
        "@operational-space-controller//:operational_space_controller",
        "@unitree-bazel//:unitree_go2_api",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "logger",
    srcs = ["logger.h"],
    deps = [
        ":aliases",
        ":containers",
        "@operational-space-controller//:operational_space_controller",
        "@abseil-cpp//absl/log:log",
        "@abseil-cpp//absl/log:log_sink",
        "@abseil-cpp//absl/log:log_sink_registry",
        "@abseil-cpp//absl/log:initialize",
        "@abseil-cpp//absl/strings:string_view",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "safety_controller",
    hdrs = ["safety_controller.h"],
    deps = [
        ":aliases",
        ":containers",
        "@operational-space-controller//:operational_space_controller",
        "@eigen//:eigen",
        "@abseil-cpp//absl/log:absl_check",
        "@abseil-cpp//absl/status:status",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "interface",
    srcs = ["interface.h"],
    deps = [
        ":aliases",
        ":containers",
        ":constants",
        ":logger",
        ":safety_controller",
        "//interface/estimators:imu_estimator",
        "@unitree-bazel//:unitree_go2_api",
        "@operational-space-controller//:operational_space_controller",
        "@mujoco-bazel//:mujoco",
        "@eigen//:eigen",
        "@osqp-cpp//:osqp++",
        "@abseil-cpp//absl/log:absl_check",
        "@abseil-cpp//absl/status:status",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "mock_unitree_driver",
    srcs = ["mock_unitree_driver.h"],
    deps = [
        ":aliases",
        ":containers",
        ":constants",
        "@unitree-bazel//:unitree_go2_api",
        "@operational-space-controller//:operational_space_controller",
        "@mujoco-bazel//:mujoco",
        "@eigen//:eigen",
        "@osqp-cpp//:osqp++",
        "@abseil-cpp//absl/log:absl_check",
        "@abseil-cpp//absl/status:status",
        "@abseil-cpp//absl/random:random",
    ],
    visibility = ["//visibility:public"],
)
