load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "onnx_test",
    srcs = ["onnx_test.cc"],
    data = ["//onnx_models:onnx_models"],
    deps = [
        "@onnxruntime-bazel//:onnxruntime",
        "@rules_cc//cc/runfiles:runfiles",
        "@bazel_tools//tools/cpp/runfiles",
    ],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "policy_test",
    srcs = ["policy_test.cc"],
    data = [
        "//onnx_models:onnx_models",
        "@mujoco-models//:unitree_go2",
    ],
    deps = [
        "//interface/unitree_go2:aliases",
        "//interface/unitree_go2:containers",
        "//interface/unitree_go2:constants",
        "//interface/unitree_go2:mock_unitree_driver",
        "//interface/unitree_go2:policy_interface",
        "@mujoco-bazel//:mujoco",
        "@eigen//:eigen",
        "@glfw-bazel//:glfw",
        "@onnxruntime-bazel//:onnxruntime",
        "@abseil-cpp//absl/log:absl_check",
        "@abseil-cpp//absl/status:status",
        "@rules_cc//cc/runfiles:runfiles",
        "@bazel_tools//tools/cpp/runfiles",
    ],
    visibility = ["//visibility:public"],
)