load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "estimator_test",
    srcs = ["estimator_test.cc"],
    data = ["@mujoco-models//:unitree_go2"],
    deps = [
        "//interface/estimators:imu_estimator",
        "//interface/unitree_go2:aliases",
        "//interface/unitree_go2:containers",
        "//interface/unitree_go2:mock_unitree_driver",
        "@mujoco-bazel//:mujoco",
        "@eigen//:eigen",
        "@abseil-cpp//absl/log:absl_check",
        "@abseil-cpp//absl/status:status",
        "@rules_cc//cc/runfiles:runfiles",
        "@bazel_tools//tools/cpp/runfiles",
    ],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "estimator_sim_test",
    srcs = ["estimator_sim_test.cc"],
    data = ["@mujoco-models//:unitree_go2"],
    deps = [
        "//interface/estimators:imu_estimator",
        "//interface/unitree_go2:aliases",
        "//interface/unitree_go2:containers",
        "//interface/unitree_go2:mock_unitree_driver",
        "@mujoco-bazel//:mujoco",
        "@eigen//:eigen",
        "@glfw-bazel//:glfw",
        "@unitree-bazel//:unitree_go2_api",
        "@abseil-cpp//absl/log:absl_check",
        "@abseil-cpp//absl/status:status",
        "@rules_cc//cc/runfiles:runfiles",
        "@bazel_tools//tools/cpp/runfiles",
    ],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "estimator_osc_test",
    srcs = ["estimator_osc_test.cc"],
    data = ["@mujoco-models//:unitree_go2"],
    deps = [
        "//interface/estimators:imu_estimator",
        "//interface/unitree_go2:interface",
        "//interface/unitree_go2:aliases",
        "//interface/unitree_go2:containers",
        "//interface/unitree_go2:mock_unitree_driver",
        "@mujoco-bazel//:mujoco",
        "@eigen//:eigen",
        "@glfw-bazel//:glfw",
        "@unitree-bazel//:unitree_go2_api",
        "@abseil-cpp//absl/log:absl_check",
        "@abseil-cpp//absl/status:status",
        "@rules_cc//cc/runfiles:runfiles",
        "@bazel_tools//tools/cpp/runfiles",
    ],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "safety_controller_test",
    srcs = ["safety_controller_test.cc"],
    data = ["@mujoco-models//:unitree_go2"],
    deps = [
        "//interface/unitree_go2:aliases",
        "//interface/unitree_go2:containers",
        "//interface/unitree_go2:constants",
        "//interface/unitree_go2:safety_controller",
        "@mujoco-bazel//:mujoco",
        "@eigen//:eigen",
        "@glfw-bazel//:glfw",
        "@abseil-cpp//absl/log:absl_check",
        "@abseil-cpp//absl/status:status",
        "@rules_cc//cc/runfiles:runfiles",
        "@bazel_tools//tools/cpp/runfiles",
    ],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "osc_simulation_test",
    srcs = ["osc_simulation_test.cc"],
    data = ["@mujoco-models//:unitree_go2"],
    deps = [
        "//interface/estimators:imu_estimator",
        "//interface/unitree_go2:aliases",
        "//interface/unitree_go2:containers",
        "//interface/unitree_go2:constants",
        "//interface/unitree_go2:mock_unitree_driver",
        "//interface/unitree_go2:interface",
        "@mujoco-bazel//:mujoco",
        "@eigen//:eigen",
        "@glfw-bazel//:glfw",
        "@abseil-cpp//absl/log:absl_check",
        "@abseil-cpp//absl/status:status",
        "@rules_cc//cc/runfiles:runfiles",
        "@bazel_tools//tools/cpp/runfiles",
    ],
    visibility = ["//visibility:public"],
)
